#【【【广东亚太】】】生产环境Tomcat端口配置
server:
  port: 80

spring:
  profiles:
    include: prod-base #引入其他配置文件
  datasource:
    url: jdbc:postgresql://122.112.193.222:5432/tz_gdyt?currentSchema=gdyt&allowMultiQueries=true #部署数据库连接
    password: 4WY7lCKDd #密码
    username: gdyt #账号

kkfileview:
  ip: 121.37.159.71
  port: 8012

collocate:
  business:
    userName: admin #超级用户
    defaultCorp: YT #登录页面展示的默认账套