#【【【哥爱帮】】】开发环境Tomcat端口配置
server:
  port: 80
  servlet:
    session:
      timeout: 600000
spring:
  profiles:
    active: jdbc,thymeleaf,devtools,logging
  main:
    allow-bean-definition-overriding: true #同名bean，后定义的bean会覆盖之前定义的相同名称的bean
  mvc:
    static-path-pattern: /static/**
  mail:
    host: smtp.qq.com
  datasource:
    url: jdbc:postgresql://121.36.196.113:5432/TZDB?currentSchema=gab #部署数据库连接
    password: 'kfyh' #密码
    username: 'kfyh' #账号


kkfileview:
  ip: 124.70.136.207
  port: 8012

collocate:
  business:
    userName: 1001,T20050014 #超级用户
    defaultCorp: JD #登录页面展示的默认账套

tengzhi:
  security:
    browser:
      maxSessions: 1 #同一个账号最多允许多少个session
      cache: false # 禁用spring.security的缓存管理，因为默认的缓存管理会在http头追加参数，使得请求无法被缓存
